services:
  web:
    build: .
    env_file: .env
    image: ghcr.io/pygreece/discord:${GIT_SHA:-latest}
    command: python -m bot
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
      image: postgres:17
      environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
        POSTGRES_DB: discord
        POSTGRES_PORT: 5432
        POSTGRES_HOST_AUTH_METHOD: trust
      volumes:
        - postgres_data:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U user -d discord"]
        interval: 5s
        timeout: 3s
        retries: 5

volumes:
  postgres_data:
