"""change ticket_id to String(5)

Revision ID: b1696cece728
Revises: f705df78a1eb
Create Date: 2026-09-29 11:13:59.457711

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b1696cece728"
down_revision: Union[str, None] = "f705df78a1eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_members_ticket_id", "members")
    op.drop_column("members", "ticket_id")
    op.alter_column(
        "tickets",
        "id",
        existing_type=sa.BIGINT(),
        type_=sa.String(length=5),
        existing_nullable=False,
    )
    op.add_column("members", sa.Column("ticket_id", sa.String(5), nullable=True))
    op.create_foreign_key("fk_members_ticket_id", "members", "tickets", ["ticket_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_members_ticket_id", table_name="members")
    op.drop_column("members", "ticket_id")
    op.alter_column(
        "tickets",
        "id",
        existing_type=sa.String(length=5),
        type_=sa.BIGINT(),
        existing_nullable=False,
    )
    op.add_column("members", sa.Column("ticket_id", sa.BIGINT(), nullable=True))
    op.create_foreign_key("fk_members_ticket_id", "members", "tickets", ["ticket_id"], ["id"])
    # ### end Alembic commands ###
