"""initial

Revision ID: cf5491e3f4d5
Revises:
Create Date: 2025-03-29 19:18:49.896573

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cf5491e3f4d5"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "members",
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("dm_sent", sa.Boolean(), nullable=False),
        sa.Column("reacted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("members")
    # ### end Alembic commands ###
