"""Add tickets table and ticket column in member table

Revision ID: f705df78a1eb
Revises: cf5491e3f4d5
Create Date: 2025-08-22 14:35:21.409411

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f705df78a1eb"
down_revision: Union[str, None] = "cf5491e3f4d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tickets",
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("members", sa.Column("ticket_id", sa.BigInteger(), nullable=True))
    op.create_foreign_key("fk_members_ticket_id", "members", "tickets", ["ticket_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_members_ticket_id", "members", type_="foreignkey")
    op.drop_column("members", "ticket_id")
    op.drop_table("tickets")
    # ### end Alembic commands ###
