name: Type checker

on:
  pull_request:
    branches: [main]

jobs:
  mypy:
    name: mypy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@f94ec6bedd8674c4426838e6b50417d36b6ab231 # v5.3.1
        with:
          python-version: 3.12

      - name: Run mypy
        run: uv run mypy
