name: Release

on:
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  build-push:
    name: 📦 Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: docker/setup-buildx-action@f7ce87c1d6bead3e36075b2ce75da1f6cc28aaca # v3.9.0
      - uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@ca877d9245402d1537745e0e356eab47c3520991 # v6.13.0
        with:
          context: .
          push: true
          tags: |
            ghcr.io/pygreece/discord:${{ github.event.release.name }}
            ghcr.io/pygreece/discord:stable
          cache-from: type=gha
          cache-to: type=gha,mode=max
